/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthenticateWithGoogle201,
  AuthenticateWithGoogleBody,
  AuthenticateWithPassword201,
  AuthenticateWithPasswordBody,
  Checkout200,
  CheckoutBody,
  CreateAddress201,
  CreateAddressBody,
  CreateCoupon201,
  CreateCouponBody,
  CreateOrder201,
  CreateOrderBody,
  CreateProduct201,
  CreateProductBody,
  CreateUser201,
  CreateUserBody,
  DeleteOrder204,
  DeleteProduct204,
  GetAddressById200,
  GetAddresses200,
  GetAddressesByUser200,
  GetCouponById200,
  GetCoupons200,
  GetCouponsParams,
  GetOrderById200,
  GetOrders200,
  GetOrdersByCustomer200,
  GetOrdersByCustomerParams,
  GetOrdersParams,
  GetProductBySlug200,
  GetProducts200,
  GetProductsParams,
  GetProfile200,
  GetUsers200,
  GetUsersParams,
  RequestPasswordRecover201,
  RequestPasswordRecoverBody,
  ResetPassword204,
  ResetPasswordBody,
  UpdateAddress204,
  UpdateAddressBody,
  UpdateCoupon204,
  UpdateCouponBody,
  UpdateOrder204,
  UpdateOrderBody,
  UpdateProduct204,
  UpdateProductBody,
  UpdateStatusCoupon204,
  UpdateUser204,
  UpdateUserBody,
  ValidateCoupon200,
  ValidateCouponBody
} from './model';

import { customInstanceMutator } from '../../utils/ky-client';
/**
 * @summary Create product
 */
export type createProductResponse201 = {
  data: CreateProduct201
  status: 201
}
    
export type createProductResponseSuccess = (createProductResponse201) & {
  headers: Headers;
};
;

export type createProductResponse = (createProductResponseSuccess)

export const getCreateProductUrl = () => {


  

  return `/products`
}

export const createProduct = async (createProductBody: CreateProductBody, options?: RequestInit): Promise<createProductResponse> => {
  
  return customInstanceMutator<createProductResponse>(getCreateProductUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProductBody,)
  }
);}



/**
 * @summary List products
 */
export type getProductsResponse200 = {
  data: GetProducts200
  status: 200
}
    
export type getProductsResponseSuccess = (getProductsResponse200) & {
  headers: Headers;
};
;

export type getProductsResponse = (getProductsResponseSuccess)

export const getGetProductsUrl = (params?: GetProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/products?${stringifiedParams}` : `/products`
}

export const getProducts = async (params?: GetProductsParams, options?: RequestInit): Promise<getProductsResponse> => {
  
  return customInstanceMutator<getProductsResponse>(getGetProductsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get product by slug
 */
export type getProductBySlugResponse200 = {
  data: GetProductBySlug200
  status: 200
}
    
export type getProductBySlugResponseSuccess = (getProductBySlugResponse200) & {
  headers: Headers;
};
;

export type getProductBySlugResponse = (getProductBySlugResponseSuccess)

export const getGetProductBySlugUrl = (slug: string,) => {


  

  return `/products/${slug}`
}

export const getProductBySlug = async (slug: string, options?: RequestInit): Promise<getProductBySlugResponse> => {
  
  return customInstanceMutator<getProductBySlugResponse>(getGetProductBySlugUrl(slug),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update product
 */
export type updateProductResponse204 = {
  data: UpdateProduct204
  status: 204
}
    
export type updateProductResponseSuccess = (updateProductResponse204) & {
  headers: Headers;
};
;

export type updateProductResponse = (updateProductResponseSuccess)

export const getUpdateProductUrl = (id: string,) => {


  

  return `/products/${id}`
}

export const updateProduct = async (id: string,
    updateProductBody: UpdateProductBody, options?: RequestInit): Promise<updateProductResponse> => {
  
  return customInstanceMutator<updateProductResponse>(getUpdateProductUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProductBody,)
  }
);}



/**
 * @summary Delete product
 */
export type deleteProductResponse204 = {
  data: DeleteProduct204
  status: 204
}
    
export type deleteProductResponseSuccess = (deleteProductResponse204) & {
  headers: Headers;
};
;

export type deleteProductResponse = (deleteProductResponseSuccess)

export const getDeleteProductUrl = (id: string,) => {


  

  return `/products/${id}`
}

export const deleteProduct = async (id: string, options?: RequestInit): Promise<deleteProductResponse> => {
  
  return customInstanceMutator<deleteProductResponse>(getDeleteProductUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Create order
 */
export type createOrderResponse201 = {
  data: CreateOrder201
  status: 201
}
    
export type createOrderResponseSuccess = (createOrderResponse201) & {
  headers: Headers;
};
;

export type createOrderResponse = (createOrderResponseSuccess)

export const getCreateOrderUrl = () => {


  

  return `/orders`
}

export const createOrder = async (createOrderBody: CreateOrderBody, options?: RequestInit): Promise<createOrderResponse> => {
  
  return customInstanceMutator<createOrderResponse>(getCreateOrderUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderBody,)
  }
);}



/**
 * @summary List all orders
 */
export type getOrdersResponse200 = {
  data: GetOrders200
  status: 200
}
    
export type getOrdersResponseSuccess = (getOrdersResponse200) & {
  headers: Headers;
};
;

export type getOrdersResponse = (getOrdersResponseSuccess)

export const getGetOrdersUrl = (params?: GetOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/orders?${stringifiedParams}` : `/orders`
}

export const getOrders = async (params?: GetOrdersParams, options?: RequestInit): Promise<getOrdersResponse> => {
  
  return customInstanceMutator<getOrdersResponse>(getGetOrdersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update order
 */
export type updateOrderResponse204 = {
  data: UpdateOrder204
  status: 204
}
    
export type updateOrderResponseSuccess = (updateOrderResponse204) & {
  headers: Headers;
};
;

export type updateOrderResponse = (updateOrderResponseSuccess)

export const getUpdateOrderUrl = (id: string,) => {


  

  return `/orders/${id}`
}

export const updateOrder = async (id: string,
    updateOrderBody: UpdateOrderBody, options?: RequestInit): Promise<updateOrderResponse> => {
  
  return customInstanceMutator<updateOrderResponse>(getUpdateOrderUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrderBody,)
  }
);}



/**
 * @summary Delete an order
 */
export type deleteOrderResponse204 = {
  data: DeleteOrder204
  status: 204
}
    
export type deleteOrderResponseSuccess = (deleteOrderResponse204) & {
  headers: Headers;
};
;

export type deleteOrderResponse = (deleteOrderResponseSuccess)

export const getDeleteOrderUrl = (id: string,) => {


  

  return `/orders/${id}`
}

export const deleteOrder = async (id: string, options?: RequestInit): Promise<deleteOrderResponse> => {
  
  return customInstanceMutator<deleteOrderResponse>(getDeleteOrderUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get order by ID
 */
export type getOrderByIdResponse200 = {
  data: GetOrderById200
  status: 200
}
    
export type getOrderByIdResponseSuccess = (getOrderByIdResponse200) & {
  headers: Headers;
};
;

export type getOrderByIdResponse = (getOrderByIdResponseSuccess)

export const getGetOrderByIdUrl = (id: string,) => {


  

  return `/orders/${id}`
}

export const getOrderById = async (id: string, options?: RequestInit): Promise<getOrderByIdResponse> => {
  
  return customInstanceMutator<getOrderByIdResponse>(getGetOrderByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get customer orders
 */
export type getOrdersByCustomerResponse200 = {
  data: GetOrdersByCustomer200
  status: 200
}
    
export type getOrdersByCustomerResponseSuccess = (getOrdersByCustomerResponse200) & {
  headers: Headers;
};
;

export type getOrdersByCustomerResponse = (getOrdersByCustomerResponseSuccess)

export const getGetOrdersByCustomerUrl = (params?: GetOrdersByCustomerParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/orders/customer?${stringifiedParams}` : `/orders/customer`
}

export const getOrdersByCustomer = async (params?: GetOrdersByCustomerParams, options?: RequestInit): Promise<getOrdersByCustomerResponse> => {
  
  return customInstanceMutator<getOrdersByCustomerResponse>(getGetOrdersByCustomerUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create user
 */
export type createUserResponse201 = {
  data: CreateUser201
  status: 201
}
    
export type createUserResponseSuccess = (createUserResponse201) & {
  headers: Headers;
};
;

export type createUserResponse = (createUserResponseSuccess)

export const getCreateUserUrl = () => {


  

  return `/user`
}

export const createUser = async (createUserBody: CreateUserBody, options?: RequestInit): Promise<createUserResponse> => {
  
  return customInstanceMutator<createUserResponse>(getCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserBody,)
  }
);}



/**
 * @summary Update user
 */
export type updateUserResponse204 = {
  data: UpdateUser204
  status: 204
}
    
export type updateUserResponseSuccess = (updateUserResponse204) & {
  headers: Headers;
};
;

export type updateUserResponse = (updateUserResponseSuccess)

export const getUpdateUserUrl = () => {


  

  return `/user`
}

export const updateUser = async (updateUserBody: UpdateUserBody, options?: RequestInit): Promise<updateUserResponse> => {
  
  return customInstanceMutator<updateUserResponse>(getUpdateUserUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserBody,)
  }
);}



/**
 * @summary Get authenticated user profile.
 */
export type getProfileResponse200 = {
  data: GetProfile200
  status: 200
}
    
export type getProfileResponseSuccess = (getProfileResponse200) & {
  headers: Headers;
};
;

export type getProfileResponse = (getProfileResponseSuccess)

export const getGetProfileUrl = () => {


  

  return `/profile`
}

export const getProfile = async ( options?: RequestInit): Promise<getProfileResponse> => {
  
  return customInstanceMutator<getProfileResponse>(getGetProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get users.
 */
export type getUsersResponse200 = {
  data: GetUsers200
  status: 200
}
    
export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
;

export type getUsersResponse = (getUsersResponseSuccess)

export const getGetUsersUrl = (params?: GetUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`
}

export const getUsers = async (params?: GetUsersParams, options?: RequestInit): Promise<getUsersResponse> => {
  
  return customInstanceMutator<getUsersResponse>(getGetUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Password Reset.
 */
export type resetPasswordResponse204 = {
  data: ResetPassword204
  status: 204
}
    
export type resetPasswordResponseSuccess = (resetPasswordResponse204) & {
  headers: Headers;
};
;

export type resetPasswordResponse = (resetPasswordResponseSuccess)

export const getResetPasswordUrl = () => {


  

  return `/password/reset`
}

export const resetPassword = async (resetPasswordBody: ResetPasswordBody, options?: RequestInit): Promise<resetPasswordResponse> => {
  
  return customInstanceMutator<resetPasswordResponse>(getResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordBody,)
  }
);}



/**
 * @summary Password Recover.
 */
export type requestPasswordRecoverResponse201 = {
  data: RequestPasswordRecover201
  status: 201
}
    
export type requestPasswordRecoverResponseSuccess = (requestPasswordRecoverResponse201) & {
  headers: Headers;
};
;

export type requestPasswordRecoverResponse = (requestPasswordRecoverResponseSuccess)

export const getRequestPasswordRecoverUrl = () => {


  

  return `/password/recover`
}

export const requestPasswordRecover = async (requestPasswordRecoverBody: RequestPasswordRecoverBody, options?: RequestInit): Promise<requestPasswordRecoverResponse> => {
  
  return customInstanceMutator<requestPasswordRecoverResponse>(getRequestPasswordRecoverUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestPasswordRecoverBody,)
  }
);}



/**
 * @summary Authenticate with Google.
 */
export type authenticateWithGoogleResponse201 = {
  data: AuthenticateWithGoogle201
  status: 201
}
    
export type authenticateWithGoogleResponseSuccess = (authenticateWithGoogleResponse201) & {
  headers: Headers;
};
;

export type authenticateWithGoogleResponse = (authenticateWithGoogleResponseSuccess)

export const getAuthenticateWithGoogleUrl = () => {


  

  return `/sessions/google`
}

export const authenticateWithGoogle = async (authenticateWithGoogleBody: AuthenticateWithGoogleBody, options?: RequestInit): Promise<authenticateWithGoogleResponse> => {
  
  return customInstanceMutator<authenticateWithGoogleResponse>(getAuthenticateWithGoogleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authenticateWithGoogleBody,)
  }
);}



/**
 * @summary Authenticate with e-mail & password.
 */
export type authenticateWithPasswordResponse201 = {
  data: AuthenticateWithPassword201
  status: 201
}
    
export type authenticateWithPasswordResponseSuccess = (authenticateWithPasswordResponse201) & {
  headers: Headers;
};
;

export type authenticateWithPasswordResponse = (authenticateWithPasswordResponseSuccess)

export const getAuthenticateWithPasswordUrl = () => {


  

  return `/sessions/password`
}

export const authenticateWithPassword = async (authenticateWithPasswordBody: AuthenticateWithPasswordBody, options?: RequestInit): Promise<authenticateWithPasswordResponse> => {
  
  return customInstanceMutator<authenticateWithPasswordResponse>(getAuthenticateWithPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authenticateWithPasswordBody,)
  }
);}



/**
 * @summary Checkout cart
 */
export type checkoutResponse200 = {
  data: Checkout200
  status: 200
}
    
export type checkoutResponseSuccess = (checkoutResponse200) & {
  headers: Headers;
};
;

export type checkoutResponse = (checkoutResponseSuccess)

export const getCheckoutUrl = () => {


  

  return `/cart/checkout`
}

export const checkout = async (checkoutBody: CheckoutBody, options?: RequestInit): Promise<checkoutResponse> => {
  
  return customInstanceMutator<checkoutResponse>(getCheckoutUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      checkoutBody,)
  }
);}



/**
 * @summary Create coupon
 */
export type createCouponResponse201 = {
  data: CreateCoupon201
  status: 201
}
    
export type createCouponResponseSuccess = (createCouponResponse201) & {
  headers: Headers;
};
;

export type createCouponResponse = (createCouponResponseSuccess)

export const getCreateCouponUrl = () => {


  

  return `/coupons`
}

export const createCoupon = async (createCouponBody: CreateCouponBody, options?: RequestInit): Promise<createCouponResponse> => {
  
  return customInstanceMutator<createCouponResponse>(getCreateCouponUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCouponBody,)
  }
);}



/**
 * @summary List coupons
 */
export type getCouponsResponse200 = {
  data: GetCoupons200
  status: 200
}
    
export type getCouponsResponseSuccess = (getCouponsResponse200) & {
  headers: Headers;
};
;

export type getCouponsResponse = (getCouponsResponseSuccess)

export const getGetCouponsUrl = (params?: GetCouponsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/coupons?${stringifiedParams}` : `/coupons`
}

export const getCoupons = async (params?: GetCouponsParams, options?: RequestInit): Promise<getCouponsResponse> => {
  
  return customInstanceMutator<getCouponsResponse>(getGetCouponsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update coupon
 */
export type updateCouponResponse204 = {
  data: UpdateCoupon204
  status: 204
}
    
export type updateCouponResponseSuccess = (updateCouponResponse204) & {
  headers: Headers;
};
;

export type updateCouponResponse = (updateCouponResponseSuccess)

export const getUpdateCouponUrl = (id: string,) => {


  

  return `/coupons/${id}`
}

export const updateCoupon = async (id: string,
    updateCouponBody: UpdateCouponBody, options?: RequestInit): Promise<updateCouponResponse> => {
  
  return customInstanceMutator<updateCouponResponse>(getUpdateCouponUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCouponBody,)
  }
);}



/**
 * @summary Delete coupon
 */
export type deleteCouponResponse200 = {
  data: void
  status: 200
}
    
export type deleteCouponResponseSuccess = (deleteCouponResponse200) & {
  headers: Headers;
};
;

export type deleteCouponResponse = (deleteCouponResponseSuccess)

export const getDeleteCouponUrl = (id: string,) => {


  

  return `/coupons/${id}`
}

export const deleteCoupon = async (id: string, options?: RequestInit): Promise<deleteCouponResponse> => {
  
  return customInstanceMutator<deleteCouponResponse>(getDeleteCouponUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get coupon by id
 */
export type getCouponByIdResponse200 = {
  data: GetCouponById200
  status: 200
}
    
export type getCouponByIdResponseSuccess = (getCouponByIdResponse200) & {
  headers: Headers;
};
;

export type getCouponByIdResponse = (getCouponByIdResponseSuccess)

export const getGetCouponByIdUrl = (id: string,) => {


  

  return `/coupons/${id}`
}

export const getCouponById = async (id: string, options?: RequestInit): Promise<getCouponByIdResponse> => {
  
  return customInstanceMutator<getCouponByIdResponse>(getGetCouponByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Validate coupon
 */
export type validateCouponResponse200 = {
  data: ValidateCoupon200
  status: 200
}
    
export type validateCouponResponseSuccess = (validateCouponResponse200) & {
  headers: Headers;
};
;

export type validateCouponResponse = (validateCouponResponseSuccess)

export const getValidateCouponUrl = () => {


  

  return `/coupons/validate`
}

export const validateCoupon = async (validateCouponBody: ValidateCouponBody, options?: RequestInit): Promise<validateCouponResponse> => {
  
  return customInstanceMutator<validateCouponResponse>(getValidateCouponUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      validateCouponBody,)
  }
);}



/**
 * @summary Cancel coupon
 */
export type updateStatusCouponResponse204 = {
  data: UpdateStatusCoupon204
  status: 204
}
    
export type updateStatusCouponResponseSuccess = (updateStatusCouponResponse204) & {
  headers: Headers;
};
;

export type updateStatusCouponResponse = (updateStatusCouponResponseSuccess)

export const getUpdateStatusCouponUrl = (id: string,) => {


  

  return `/coupons/${id}/status`
}

export const updateStatusCoupon = async (id: string, options?: RequestInit): Promise<updateStatusCouponResponse> => {
  
  return customInstanceMutator<updateStatusCouponResponse>(getUpdateStatusCouponUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}



/**
 * @summary Create address
 */
export type createAddressResponse201 = {
  data: CreateAddress201
  status: 201
}
    
export type createAddressResponseSuccess = (createAddressResponse201) & {
  headers: Headers;
};
;

export type createAddressResponse = (createAddressResponseSuccess)

export const getCreateAddressUrl = () => {


  

  return `/address`
}

export const createAddress = async (createAddressBody: CreateAddressBody, options?: RequestInit): Promise<createAddressResponse> => {
  
  return customInstanceMutator<createAddressResponse>(getCreateAddressUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAddressBody,)
  }
);}



/**
 * @summary Delete address
 */
export type deleteAddressResponse200 = {
  data: void
  status: 200
}
    
export type deleteAddressResponseSuccess = (deleteAddressResponse200) & {
  headers: Headers;
};
;

export type deleteAddressResponse = (deleteAddressResponseSuccess)

export const getDeleteAddressUrl = (id: string,) => {


  

  return `/addresses/${id}`
}

export const deleteAddress = async (id: string, options?: RequestInit): Promise<deleteAddressResponse> => {
  
  return customInstanceMutator<deleteAddressResponse>(getDeleteAddressUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Update address
 */
export type updateAddressResponse204 = {
  data: UpdateAddress204
  status: 204
}
    
export type updateAddressResponseSuccess = (updateAddressResponse204) & {
  headers: Headers;
};
;

export type updateAddressResponse = (updateAddressResponseSuccess)

export const getUpdateAddressUrl = (id: string,) => {


  

  return `/addresses/${id}`
}

export const updateAddress = async (id: string,
    updateAddressBody: UpdateAddressBody, options?: RequestInit): Promise<updateAddressResponse> => {
  
  return customInstanceMutator<updateAddressResponse>(getUpdateAddressUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateAddressBody,)
  }
);}



/**
 * @summary Get address by ID
 */
export type getAddressByIdResponse200 = {
  data: GetAddressById200
  status: 200
}
    
export type getAddressByIdResponseSuccess = (getAddressByIdResponse200) & {
  headers: Headers;
};
;

export type getAddressByIdResponse = (getAddressByIdResponseSuccess)

export const getGetAddressByIdUrl = (id: string,) => {


  

  return `/addresses/${id}`
}

export const getAddressById = async (id: string, options?: RequestInit): Promise<getAddressByIdResponse> => {
  
  return customInstanceMutator<getAddressByIdResponse>(getGetAddressByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get user addresses
 */
export type getAddressesResponse200 = {
  data: GetAddresses200
  status: 200
}
    
export type getAddressesResponseSuccess = (getAddressesResponse200) & {
  headers: Headers;
};
;

export type getAddressesResponse = (getAddressesResponseSuccess)

export const getGetAddressesUrl = () => {


  

  return `/addresses`
}

export const getAddresses = async ( options?: RequestInit): Promise<getAddressesResponse> => {
  
  return customInstanceMutator<getAddressesResponse>(getGetAddressesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get address by User
 */
export type getAddressesByUserResponse200 = {
  data: GetAddressesByUser200
  status: 200
}
    
export type getAddressesByUserResponseSuccess = (getAddressesByUserResponse200) & {
  headers: Headers;
};
;

export type getAddressesByUserResponse = (getAddressesByUserResponseSuccess)

export const getGetAddressesByUserUrl = () => {


  

  return `/user/addresses`
}

export const getAddressesByUser = async ( options?: RequestInit): Promise<getAddressesByUserResponse> => {
  
  return customInstanceMutator<getAddressesByUserResponse>(getGetAddressesByUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
