/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import { kyFetch } from '../../utils/ky-client';
export type PostProductsBody = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  slug: string;
  /** @minLength 1 */
  description: string;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  price: number;
  image: string;
  /** @pattern ^[cC][^\s-]{8,}$ */
  categoryId: string;
  popular?: boolean;
  available?: boolean;
};

export type PostProducts201 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  productId: string;
};

export type GetProductsParams = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @pattern ^[cC][^\s-]{8,}$
 */
categoryId?: string;
popular?: boolean;
available?: boolean;
};

export type GetProducts200ProductsItem = {
  id: string;
  name: string;
  slug: string;
  price: number;
  image: string;
  popular: boolean;
  available: boolean;
};

export type GetProducts200 = {
  products: GetProducts200ProductsItem[];
  total: number;
  page: number;
  limit: number;
};

export type GetProductsSlug200 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  image: string;
  popular: boolean;
  available: boolean;
  categoryId: string;
};

export type PutProductsIdBody = {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  slug?: string;
  description?: string;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  price?: number;
  image?: string;
  /** @pattern ^[cC][^\s-]{8,}$ */
  categoryId?: string;
  popular?: boolean;
  available?: boolean;
};

/**
 * @nullable
 */
export type PutProductsId204 = typeof PutProductsId204[keyof typeof PutProductsId204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutProductsId204 = {
} as const;

/**
 * @nullable
 */
export type DeleteProductsId204 = typeof DeleteProductsId204[keyof typeof DeleteProductsId204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteProductsId204 = {
} as const;

export type PostOrdersBodyStatus = typeof PostOrdersBodyStatus[keyof typeof PostOrdersBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrdersBodyStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type PostOrdersBodyPaymentMethod = typeof PostOrdersBodyPaymentMethod[keyof typeof PostOrdersBodyPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrdersBodyPaymentMethod = {
  CASH: 'CASH',
  PIX: 'PIX',
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
} as const;

export type PostOrdersBodyItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  productId: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  quantity: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  unitPrice: number;
};

export type PostOrdersBody = {
  status?: PostOrdersBodyStatus;
  paymentMethod: PostOrdersBodyPaymentMethod;
  /** @pattern ^[cC][^\s-]{8,}$ */
  addressId: string;
  couponCode?: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  deliveryFee?: number;
  /** @minItems 1 */
  items: PostOrdersBodyItemsItem[];
};

export type PostOrders201 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  orderId: string;
};

export type GetOrdersParams = {
page?: string;
limit?: string;
status?: GetOrdersStatus;
search?: string;
/**
 * @pattern ^[cC][^\s-]{8,}$
 */
customerId?: string;
startDate?: unknown;
endDate?: unknown;
};

export type GetOrdersStatus = typeof GetOrdersStatus[keyof typeof GetOrdersStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type GetOrders200OrdersItemStatus = typeof GetOrders200OrdersItemStatus[keyof typeof GetOrders200OrdersItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrders200OrdersItemStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type GetOrders200OrdersItemPaymentMethod = typeof GetOrders200OrdersItemPaymentMethod[keyof typeof GetOrders200OrdersItemPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrders200OrdersItemPaymentMethod = {
  CASH: 'CASH',
  PIX: 'PIX',
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
} as const;

/**
 * @nullable
 */
export type GetOrders200OrdersItemCustomer = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  phone: string | null;
} | null;

export type GetOrders200OrdersItemItemsItemProduct = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  slug: string;
};

export type GetOrders200OrdersItemItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  quantity: number;
  unitPrice: number;
  product: GetOrders200OrdersItemItemsItemProduct;
};

/**
 * @nullable
 */
export type GetOrders200OrdersItemAddress = {
  /** @nullable */
  number: number | null;
  /** @nullable */
  name: string | null;
  street: string;
  /** @nullable */
  complement: string | null;
  /** @nullable */
  neighborhood: string | null;
  city: string;
  zipCode: string;
} | null;

export type GetOrders200OrdersItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  orderNumber: number;
  status: GetOrders200OrdersItemStatus;
  paymentMethod: GetOrders200OrdersItemPaymentMethod;
  total: number;
  itemsCount: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  customer: GetOrders200OrdersItemCustomer;
  items: GetOrders200OrdersItemItemsItem[];
  /** @nullable */
  address: GetOrders200OrdersItemAddress;
};

export type GetOrders200Pagination = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limit: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  total: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
};

export type GetOrders200 = {
  orders: GetOrders200OrdersItem[];
  pagination: GetOrders200Pagination;
};

export type PutOrdersIdBodyPaymentMethod = typeof PutOrdersIdBodyPaymentMethod[keyof typeof PutOrdersIdBodyPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutOrdersIdBodyPaymentMethod = {
  CASH: 'CASH',
  PIX: 'PIX',
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
} as const;

export type PutOrdersIdBodyStatus = typeof PutOrdersIdBodyStatus[keyof typeof PutOrdersIdBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutOrdersIdBodyStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type PutOrdersIdBodyItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  productId: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  quantity: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  unitPrice: number;
};

export type PutOrdersIdBody = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  addressId?: string;
  paymentMethod?: PutOrdersIdBodyPaymentMethod;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  changeFor?: number;
  status?: PutOrdersIdBodyStatus;
  /**
   * @nullable
   * @pattern ^[cC][^\s-]{8,}$
   */
  couponId?: string | null;
  items?: PutOrdersIdBodyItemsItem[];
};

/**
 * @nullable
 */
export type PutOrdersId204 = typeof PutOrdersId204[keyof typeof PutOrdersId204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutOrdersId204 = {
} as const;

/**
 * @nullable
 */
export type DeleteOrdersId204 = typeof DeleteOrdersId204[keyof typeof DeleteOrdersId204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteOrdersId204 = {
} as const;

export type GetOrdersId200OrderStatus = typeof GetOrdersId200OrderStatus[keyof typeof GetOrdersId200OrderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersId200OrderStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type GetOrdersId200OrderPaymentMethod = typeof GetOrdersId200OrderPaymentMethod[keyof typeof GetOrdersId200OrderPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersId200OrderPaymentMethod = {
  CASH: 'CASH',
  PIX: 'PIX',
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
} as const;

export type GetOrdersId200OrderItemsItemProduct = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  slug: string;
};

export type GetOrdersId200OrderItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  quantity: number;
  unitPrice: number;
  product: GetOrdersId200OrderItemsItemProduct;
};

export type GetOrdersId200OrderCustomer = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  phone: string | null;
};

export type GetOrdersId200OrderAddress = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  street: string;
  /** @nullable */
  number: number | null;
  /** @nullable */
  complement: string | null;
  neighborhood: string;
  city: string;
  zipCode: string;
};

export type GetOrdersId200Order = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  orderNumber: number;
  status: GetOrdersId200OrderStatus;
  paymentMethod: GetOrdersId200OrderPaymentMethod;
  items: GetOrdersId200OrderItemsItem[];
  itemsCount: number;
  itemsTotal: number;
  deliveryFee: number;
  total: number;
  createdAt: string;
  updatedAt: string;
  customer: GetOrdersId200OrderCustomer;
  address: GetOrdersId200OrderAddress;
};

export type GetOrdersId200 = {
  order: GetOrdersId200Order;
};

export type GetOrdersCustomerParams = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
status?: GetOrdersCustomerStatus;
};

export type GetOrdersCustomerStatus = typeof GetOrdersCustomerStatus[keyof typeof GetOrdersCustomerStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersCustomerStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type GetOrdersCustomer200OrdersItemStatus = typeof GetOrdersCustomer200OrdersItemStatus[keyof typeof GetOrdersCustomer200OrdersItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersCustomer200OrdersItemStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type GetOrdersCustomer200OrdersItemCustomer = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  name: string | null;
};

export type GetOrdersCustomer200OrdersItemItemsItemProduct = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  slug: string;
};

export type GetOrdersCustomer200OrdersItemItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  quantity: number;
  unitPrice: number;
  product: GetOrdersCustomer200OrdersItemItemsItemProduct;
};

export type GetOrdersCustomer200OrdersItemAddress = {
  street: string;
  /** @nullable */
  number: number | null;
  /** @nullable */
  complement: string | null;
  neighborhood: string;
  city: string;
  zipCode: string;
};

export type GetOrdersCustomer200OrdersItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  status: GetOrdersCustomer200OrdersItemStatus;
  createdAt: string;
  updatedAt: string;
  total: number;
  itemsCount: number;
  customer: GetOrdersCustomer200OrdersItemCustomer;
  items: GetOrdersCustomer200OrdersItemItemsItem[];
  address: GetOrdersCustomer200OrdersItemAddress;
};

export type GetOrdersCustomer200Pagination = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limit: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  total: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
};

export type GetOrdersCustomer200 = {
  orders: GetOrdersCustomer200OrdersItem[];
  pagination: GetOrdersCustomer200Pagination;
};

export type PostUserBody = {
  /** @minLength 1 */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
};

export type PostUser201 = {
  token: string;
};

export type PutUserBody = {
  name?: string;
  phone?: string;
};

/**
 * @nullable
 */
export type PutUser204 = typeof PutUser204[keyof typeof PutUser204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutUser204 = {
} as const;

export type GetProfile200UserRole = typeof GetProfile200UserRole[keyof typeof GetProfile200UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetProfile200UserRole = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
} as const;

export type GetProfile200User = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @nullable */
  name: string | null;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  phone: string | null;
  role: GetProfile200UserRole;
};

export type GetProfile200 = {
  user: GetProfile200User;
};

export type GetUsersParams = {
role?: GetUsersRole;
page?: string;
limit?: string;
search?: string;
};

export type GetUsersRole = typeof GetUsersRole[keyof typeof GetUsersRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUsersRole = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
} as const;

export type GetUsers200UsersItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @nullable */
  name: string | null;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  city: string | null;
  joinDate: string;
};

export type GetUsers200Pagination = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limit: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  total: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
};

export type GetUsers200 = {
  users: GetUsers200UsersItem[];
  pagination: GetUsers200Pagination;
};

export type PostPasswordResetBody = {
  code: string;
  /** @minLength 6 */
  password: string;
};

/**
 * @nullable
 */
export type PostPasswordReset204 = typeof PostPasswordReset204[keyof typeof PostPasswordReset204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPasswordReset204 = {
} as const;

export type PostPasswordRecoverBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
};

/**
 * @nullable
 */
export type PostPasswordRecover201 = typeof PostPasswordRecover201[keyof typeof PostPasswordRecover201] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPasswordRecover201 = {
} as const;

export type PostSessionsGoogleBody = {
  code: string;
};

export type PostSessionsGoogle201 = {
  token: string;
};

export type PostSessionsPasswordBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
};

export type PostSessionsPassword201 = {
  token: string;
};

export type PostCartCheckoutBody = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  addressId: string;
};

export type PostCartCheckout200OrderItemsItemProduct = {
  id: string;
  name: string;
};

export type PostCartCheckout200OrderItemsItem = {
  product: PostCartCheckout200OrderItemsItemProduct;
};

/**
 * @nullable
 */
export type PostCartCheckout200Order = {
  id: string;
  items: PostCartCheckout200OrderItemsItem[];
} | null;

export type PostCartCheckout200 = {
  /** @nullable */
  order: PostCartCheckout200Order;
};

export type PostCouponsBodyType = typeof PostCouponsBodyType[keyof typeof PostCouponsBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCouponsBodyType = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
} as const;

export type PostCouponsBodyScope = typeof PostCouponsBodyScope[keyof typeof PostCouponsBodyScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCouponsBodyScope = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCTS: 'PRODUCTS',
} as const;

export type PostCouponsBody = {
  /** @minLength 1 */
  code: string;
  type: PostCouponsBodyType;
  scope: PostCouponsBodyScope;
  isActive?: boolean;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  value: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  minOrderValue?: number;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  maxUses?: number;
  expiresAt?: unknown;
  productIds?: string[];
};

export type PostCoupons201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  couponId: string;
};

export type GetCouponsParams = {
page?: string;
limit?: string;
};

export type GetCoupons200CouponsItemType = typeof GetCoupons200CouponsItemType[keyof typeof GetCoupons200CouponsItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCoupons200CouponsItemType = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
} as const;

export type GetCoupons200CouponsItemScope = typeof GetCoupons200CouponsItemScope[keyof typeof GetCoupons200CouponsItemScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCoupons200CouponsItemScope = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCTS: 'PRODUCTS',
} as const;

export type GetCoupons200CouponsItemUsagesItem = {
  id: string;
  couponId: string;
  userId: string;
  usedAt: string;
};

export type GetCoupons200CouponsItemProductsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  price: number;
  image: string;
};

export type GetCoupons200CouponsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  code: string;
  type: GetCoupons200CouponsItemType;
  scope: GetCoupons200CouponsItemScope;
  value: number;
  /** @nullable */
  minOrderValue: number | null;
  /** @nullable */
  maxUses: number | null;
  usedCount: number;
  /** @nullable */
  expiresAt: string | null;
  isActive: boolean;
  createdAt: string;
  usages: GetCoupons200CouponsItemUsagesItem[];
  products: GetCoupons200CouponsItemProductsItem[];
};

export type GetCoupons200Pagination = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limit: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  total: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
};

export type GetCoupons200 = {
  coupons: GetCoupons200CouponsItem[];
  pagination: GetCoupons200Pagination;
};

export type PutCouponsIdBodyScope = typeof PutCouponsIdBodyScope[keyof typeof PutCouponsIdBodyScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutCouponsIdBodyScope = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCTS: 'PRODUCTS',
} as const;

/**
 * @nullable
 */
export type PutCouponsIdBodyExpiresAt = unknown | null;

export type PutCouponsIdBody = {
  code?: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  value?: number;
  isActive?: boolean;
  /**
   * @minimum 0
   * @exclusiveMinimum
   * @nullable
   */
  minOrderValue?: number | null;
  scope?: PutCouponsIdBodyScope;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   * @nullable
   */
  maxUses?: number | null;
  /** @nullable */
  expiresAt?: PutCouponsIdBodyExpiresAt;
  productIds?: string[];
};

/**
 * @nullable
 */
export type PutCouponsId204 = typeof PutCouponsId204[keyof typeof PutCouponsId204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutCouponsId204 = {
} as const;

export type GetCouponsId200CouponType = typeof GetCouponsId200CouponType[keyof typeof GetCouponsId200CouponType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCouponsId200CouponType = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
} as const;

export type GetCouponsId200CouponScope = typeof GetCouponsId200CouponScope[keyof typeof GetCouponsId200CouponScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCouponsId200CouponScope = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCTS: 'PRODUCTS',
} as const;

export type GetCouponsId200CouponUsagesItem = {
  id: string;
  couponId: string;
  userId: string;
  usedAt: string;
};

export type GetCouponsId200CouponProductsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  price: number;
  image: string;
};

export type GetCouponsId200Coupon = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  code: string;
  type: GetCouponsId200CouponType;
  scope: GetCouponsId200CouponScope;
  value: number;
  /** @nullable */
  minOrderValue: number | null;
  /** @nullable */
  maxUses: number | null;
  usedCount: number;
  /** @nullable */
  expiresAt: string | null;
  isActive: boolean;
  createdAt: string;
  usages: GetCouponsId200CouponUsagesItem[];
  products: GetCouponsId200CouponProductsItem[];
};

export type GetCouponsId200 = {
  coupon: GetCouponsId200Coupon;
};

export type PostCouponsValidateBody = {
  code: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  orderTotal: number;
  /** @minItems 1 */
  productIds: string[];
};

export type PostCouponsValidate200 = {
  discount: number;
  finalTotal: number;
};

/**
 * @nullable
 */
export type PatchCouponsIdStatus204 = typeof PatchCouponsIdStatus204[keyof typeof PatchCouponsIdStatus204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchCouponsIdStatus204 = {
} as const;

/**
 * @summary Create product
 */
export type postProductsResponse201 = {
  data: PostProducts201
  status: 201
}
    
export type postProductsResponseSuccess = (postProductsResponse201) & {
  headers: Headers;
};
;

export type postProductsResponse = (postProductsResponseSuccess)

export const getPostProductsUrl = () => {


  

  return `/products`
}

export const postProducts = async (postProductsBody: PostProductsBody, options?: RequestInit): Promise<postProductsResponse> => {
  
  return kyFetch<postProductsResponse>(getPostProductsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postProductsBody,)
  }
);}



/**
 * @summary List products
 */
export type getProductsResponse200 = {
  data: GetProducts200
  status: 200
}
    
export type getProductsResponseSuccess = (getProductsResponse200) & {
  headers: Headers;
};
;

export type getProductsResponse = (getProductsResponseSuccess)

export const getGetProductsUrl = (params?: GetProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/products?${stringifiedParams}` : `/products`
}

export const getProducts = async (params?: GetProductsParams, options?: RequestInit): Promise<getProductsResponse> => {
  
  return kyFetch<getProductsResponse>(getGetProductsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get product by slug
 */
export type getProductsSlugResponse200 = {
  data: GetProductsSlug200
  status: 200
}
    
export type getProductsSlugResponseSuccess = (getProductsSlugResponse200) & {
  headers: Headers;
};
;

export type getProductsSlugResponse = (getProductsSlugResponseSuccess)

export const getGetProductsSlugUrl = (slug: string,) => {


  

  return `/products/${slug}`
}

export const getProductsSlug = async (slug: string, options?: RequestInit): Promise<getProductsSlugResponse> => {
  
  return kyFetch<getProductsSlugResponse>(getGetProductsSlugUrl(slug),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update product
 */
export type putProductsIdResponse204 = {
  data: PutProductsId204
  status: 204
}
    
export type putProductsIdResponseSuccess = (putProductsIdResponse204) & {
  headers: Headers;
};
;

export type putProductsIdResponse = (putProductsIdResponseSuccess)

export const getPutProductsIdUrl = (id: string,) => {


  

  return `/products/${id}`
}

export const putProductsId = async (id: string,
    putProductsIdBody: PutProductsIdBody, options?: RequestInit): Promise<putProductsIdResponse> => {
  
  return kyFetch<putProductsIdResponse>(getPutProductsIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putProductsIdBody,)
  }
);}



/**
 * @summary Delete product
 */
export type deleteProductsIdResponse204 = {
  data: DeleteProductsId204
  status: 204
}
    
export type deleteProductsIdResponseSuccess = (deleteProductsIdResponse204) & {
  headers: Headers;
};
;

export type deleteProductsIdResponse = (deleteProductsIdResponseSuccess)

export const getDeleteProductsIdUrl = (id: string,) => {


  

  return `/products/${id}`
}

export const deleteProductsId = async (id: string, options?: RequestInit): Promise<deleteProductsIdResponse> => {
  
  return kyFetch<deleteProductsIdResponse>(getDeleteProductsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Create order
 */
export type postOrdersResponse201 = {
  data: PostOrders201
  status: 201
}
    
export type postOrdersResponseSuccess = (postOrdersResponse201) & {
  headers: Headers;
};
;

export type postOrdersResponse = (postOrdersResponseSuccess)

export const getPostOrdersUrl = () => {


  

  return `/orders`
}

export const postOrders = async (postOrdersBody: PostOrdersBody, options?: RequestInit): Promise<postOrdersResponse> => {
  
  return kyFetch<postOrdersResponse>(getPostOrdersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postOrdersBody,)
  }
);}



/**
 * @summary List all orders
 */
export type getOrdersResponse200 = {
  data: GetOrders200
  status: 200
}
    
export type getOrdersResponseSuccess = (getOrdersResponse200) & {
  headers: Headers;
};
;

export type getOrdersResponse = (getOrdersResponseSuccess)

export const getGetOrdersUrl = (params?: GetOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/orders?${stringifiedParams}` : `/orders`
}

export const getOrders = async (params?: GetOrdersParams, options?: RequestInit): Promise<getOrdersResponse> => {
  
  return kyFetch<getOrdersResponse>(getGetOrdersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update order
 */
export type putOrdersIdResponse204 = {
  data: PutOrdersId204
  status: 204
}
    
export type putOrdersIdResponseSuccess = (putOrdersIdResponse204) & {
  headers: Headers;
};
;

export type putOrdersIdResponse = (putOrdersIdResponseSuccess)

export const getPutOrdersIdUrl = (id: string,) => {


  

  return `/orders/${id}`
}

export const putOrdersId = async (id: string,
    putOrdersIdBody: PutOrdersIdBody, options?: RequestInit): Promise<putOrdersIdResponse> => {
  
  return kyFetch<putOrdersIdResponse>(getPutOrdersIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putOrdersIdBody,)
  }
);}



/**
 * @summary Delete an order
 */
export type deleteOrdersIdResponse204 = {
  data: DeleteOrdersId204
  status: 204
}
    
export type deleteOrdersIdResponseSuccess = (deleteOrdersIdResponse204) & {
  headers: Headers;
};
;

export type deleteOrdersIdResponse = (deleteOrdersIdResponseSuccess)

export const getDeleteOrdersIdUrl = (id: string,) => {


  

  return `/orders/${id}`
}

export const deleteOrdersId = async (id: string, options?: RequestInit): Promise<deleteOrdersIdResponse> => {
  
  return kyFetch<deleteOrdersIdResponse>(getDeleteOrdersIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get order by ID
 */
export type getOrdersIdResponse200 = {
  data: GetOrdersId200
  status: 200
}
    
export type getOrdersIdResponseSuccess = (getOrdersIdResponse200) & {
  headers: Headers;
};
;

export type getOrdersIdResponse = (getOrdersIdResponseSuccess)

export const getGetOrdersIdUrl = (id: string,) => {


  

  return `/orders/${id}`
}

export const getOrdersId = async (id: string, options?: RequestInit): Promise<getOrdersIdResponse> => {
  
  return kyFetch<getOrdersIdResponse>(getGetOrdersIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get customer orders
 */
export type getOrdersCustomerResponse200 = {
  data: GetOrdersCustomer200
  status: 200
}
    
export type getOrdersCustomerResponseSuccess = (getOrdersCustomerResponse200) & {
  headers: Headers;
};
;

export type getOrdersCustomerResponse = (getOrdersCustomerResponseSuccess)

export const getGetOrdersCustomerUrl = (params?: GetOrdersCustomerParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/orders/customer?${stringifiedParams}` : `/orders/customer`
}

export const getOrdersCustomer = async (params?: GetOrdersCustomerParams, options?: RequestInit): Promise<getOrdersCustomerResponse> => {
  
  return kyFetch<getOrdersCustomerResponse>(getGetOrdersCustomerUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create user
 */
export type postUserResponse201 = {
  data: PostUser201
  status: 201
}
    
export type postUserResponseSuccess = (postUserResponse201) & {
  headers: Headers;
};
;

export type postUserResponse = (postUserResponseSuccess)

export const getPostUserUrl = () => {


  

  return `/user`
}

export const postUser = async (postUserBody: PostUserBody, options?: RequestInit): Promise<postUserResponse> => {
  
  return kyFetch<postUserResponse>(getPostUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postUserBody,)
  }
);}



/**
 * @summary Update user
 */
export type putUserResponse204 = {
  data: PutUser204
  status: 204
}
    
export type putUserResponseSuccess = (putUserResponse204) & {
  headers: Headers;
};
;

export type putUserResponse = (putUserResponseSuccess)

export const getPutUserUrl = () => {


  

  return `/user`
}

export const putUser = async (putUserBody: PutUserBody, options?: RequestInit): Promise<putUserResponse> => {
  
  return kyFetch<putUserResponse>(getPutUserUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putUserBody,)
  }
);}



/**
 * @summary Get authenticated user profile.
 */
export type getProfileResponse200 = {
  data: GetProfile200
  status: 200
}
    
export type getProfileResponseSuccess = (getProfileResponse200) & {
  headers: Headers;
};
;

export type getProfileResponse = (getProfileResponseSuccess)

export const getGetProfileUrl = () => {


  

  return `/profile`
}

export const getProfile = async ( options?: RequestInit): Promise<getProfileResponse> => {
  
  return kyFetch<getProfileResponse>(getGetProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get users.
 */
export type getUsersResponse200 = {
  data: GetUsers200
  status: 200
}
    
export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
;

export type getUsersResponse = (getUsersResponseSuccess)

export const getGetUsersUrl = (params?: GetUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`
}

export const getUsers = async (params?: GetUsersParams, options?: RequestInit): Promise<getUsersResponse> => {
  
  return kyFetch<getUsersResponse>(getGetUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Password Reset.
 */
export type postPasswordResetResponse204 = {
  data: PostPasswordReset204
  status: 204
}
    
export type postPasswordResetResponseSuccess = (postPasswordResetResponse204) & {
  headers: Headers;
};
;

export type postPasswordResetResponse = (postPasswordResetResponseSuccess)

export const getPostPasswordResetUrl = () => {


  

  return `/password/reset`
}

export const postPasswordReset = async (postPasswordResetBody: PostPasswordResetBody, options?: RequestInit): Promise<postPasswordResetResponse> => {
  
  return kyFetch<postPasswordResetResponse>(getPostPasswordResetUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postPasswordResetBody,)
  }
);}



/**
 * @summary Password Recover.
 */
export type postPasswordRecoverResponse201 = {
  data: PostPasswordRecover201
  status: 201
}
    
export type postPasswordRecoverResponseSuccess = (postPasswordRecoverResponse201) & {
  headers: Headers;
};
;

export type postPasswordRecoverResponse = (postPasswordRecoverResponseSuccess)

export const getPostPasswordRecoverUrl = () => {


  

  return `/password/recover`
}

export const postPasswordRecover = async (postPasswordRecoverBody: PostPasswordRecoverBody, options?: RequestInit): Promise<postPasswordRecoverResponse> => {
  
  return kyFetch<postPasswordRecoverResponse>(getPostPasswordRecoverUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postPasswordRecoverBody,)
  }
);}



/**
 * @summary Authenticate with Google.
 */
export type postSessionsGoogleResponse201 = {
  data: PostSessionsGoogle201
  status: 201
}
    
export type postSessionsGoogleResponseSuccess = (postSessionsGoogleResponse201) & {
  headers: Headers;
};
;

export type postSessionsGoogleResponse = (postSessionsGoogleResponseSuccess)

export const getPostSessionsGoogleUrl = () => {


  

  return `/sessions/google`
}

export const postSessionsGoogle = async (postSessionsGoogleBody: PostSessionsGoogleBody, options?: RequestInit): Promise<postSessionsGoogleResponse> => {
  
  return kyFetch<postSessionsGoogleResponse>(getPostSessionsGoogleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postSessionsGoogleBody,)
  }
);}



/**
 * @summary Authenticate with e-mail & password.
 */
export type postSessionsPasswordResponse201 = {
  data: PostSessionsPassword201
  status: 201
}
    
export type postSessionsPasswordResponseSuccess = (postSessionsPasswordResponse201) & {
  headers: Headers;
};
;

export type postSessionsPasswordResponse = (postSessionsPasswordResponseSuccess)

export const getPostSessionsPasswordUrl = () => {


  

  return `/sessions/password`
}

export const postSessionsPassword = async (postSessionsPasswordBody: PostSessionsPasswordBody, options?: RequestInit): Promise<postSessionsPasswordResponse> => {
  
  return kyFetch<postSessionsPasswordResponse>(getPostSessionsPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postSessionsPasswordBody,)
  }
);}



/**
 * @summary Checkout cart
 */
export type postCartCheckoutResponse200 = {
  data: PostCartCheckout200
  status: 200
}
    
export type postCartCheckoutResponseSuccess = (postCartCheckoutResponse200) & {
  headers: Headers;
};
;

export type postCartCheckoutResponse = (postCartCheckoutResponseSuccess)

export const getPostCartCheckoutUrl = () => {


  

  return `/cart/checkout`
}

export const postCartCheckout = async (postCartCheckoutBody: PostCartCheckoutBody, options?: RequestInit): Promise<postCartCheckoutResponse> => {
  
  return kyFetch<postCartCheckoutResponse>(getPostCartCheckoutUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postCartCheckoutBody,)
  }
);}



/**
 * @summary Create coupon
 */
export type postCouponsResponse201 = {
  data: PostCoupons201
  status: 201
}
    
export type postCouponsResponseSuccess = (postCouponsResponse201) & {
  headers: Headers;
};
;

export type postCouponsResponse = (postCouponsResponseSuccess)

export const getPostCouponsUrl = () => {


  

  return `/coupons`
}

export const postCoupons = async (postCouponsBody: PostCouponsBody, options?: RequestInit): Promise<postCouponsResponse> => {
  
  return kyFetch<postCouponsResponse>(getPostCouponsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postCouponsBody,)
  }
);}



/**
 * @summary List coupons
 */
export type getCouponsResponse200 = {
  data: GetCoupons200
  status: 200
}
    
export type getCouponsResponseSuccess = (getCouponsResponse200) & {
  headers: Headers;
};
;

export type getCouponsResponse = (getCouponsResponseSuccess)

export const getGetCouponsUrl = (params?: GetCouponsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/coupons?${stringifiedParams}` : `/coupons`
}

export const getCoupons = async (params?: GetCouponsParams, options?: RequestInit): Promise<getCouponsResponse> => {
  
  return kyFetch<getCouponsResponse>(getGetCouponsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update coupon
 */
export type putCouponsIdResponse204 = {
  data: PutCouponsId204
  status: 204
}
    
export type putCouponsIdResponseSuccess = (putCouponsIdResponse204) & {
  headers: Headers;
};
;

export type putCouponsIdResponse = (putCouponsIdResponseSuccess)

export const getPutCouponsIdUrl = (id: string,) => {


  

  return `/coupons/${id}`
}

export const putCouponsId = async (id: string,
    putCouponsIdBody: PutCouponsIdBody, options?: RequestInit): Promise<putCouponsIdResponse> => {
  
  return kyFetch<putCouponsIdResponse>(getPutCouponsIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putCouponsIdBody,)
  }
);}



/**
 * @summary Delete coupon
 */
export type deleteCouponsIdResponse200 = {
  data: void
  status: 200
}
    
export type deleteCouponsIdResponseSuccess = (deleteCouponsIdResponse200) & {
  headers: Headers;
};
;

export type deleteCouponsIdResponse = (deleteCouponsIdResponseSuccess)

export const getDeleteCouponsIdUrl = (id: string,) => {


  

  return `/coupons/${id}`
}

export const deleteCouponsId = async (id: string, options?: RequestInit): Promise<deleteCouponsIdResponse> => {
  
  return kyFetch<deleteCouponsIdResponse>(getDeleteCouponsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get coupon by id
 */
export type getCouponsIdResponse200 = {
  data: GetCouponsId200
  status: 200
}
    
export type getCouponsIdResponseSuccess = (getCouponsIdResponse200) & {
  headers: Headers;
};
;

export type getCouponsIdResponse = (getCouponsIdResponseSuccess)

export const getGetCouponsIdUrl = (id: string,) => {


  

  return `/coupons/${id}`
}

export const getCouponsId = async (id: string, options?: RequestInit): Promise<getCouponsIdResponse> => {
  
  return kyFetch<getCouponsIdResponse>(getGetCouponsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Validate coupon
 */
export type postCouponsValidateResponse200 = {
  data: PostCouponsValidate200
  status: 200
}
    
export type postCouponsValidateResponseSuccess = (postCouponsValidateResponse200) & {
  headers: Headers;
};
;

export type postCouponsValidateResponse = (postCouponsValidateResponseSuccess)

export const getPostCouponsValidateUrl = () => {


  

  return `/coupons/validate`
}

export const postCouponsValidate = async (postCouponsValidateBody: PostCouponsValidateBody, options?: RequestInit): Promise<postCouponsValidateResponse> => {
  
  return kyFetch<postCouponsValidateResponse>(getPostCouponsValidateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postCouponsValidateBody,)
  }
);}



/**
 * @summary Cancel coupon
 */
export type patchCouponsIdStatusResponse204 = {
  data: PatchCouponsIdStatus204
  status: 204
}
    
export type patchCouponsIdStatusResponseSuccess = (patchCouponsIdStatusResponse204) & {
  headers: Headers;
};
;

export type patchCouponsIdStatusResponse = (patchCouponsIdStatusResponseSuccess)

export const getPatchCouponsIdStatusUrl = (id: string,) => {


  

  return `/coupons/${id}/status`
}

export const patchCouponsIdStatus = async (id: string, options?: RequestInit): Promise<patchCouponsIdStatusResponse> => {
  
  return kyFetch<patchCouponsIdStatusResponse>(getPatchCouponsIdStatusUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}
