/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { Checkout200OrderItemsItemProduct } from './checkout200OrderItemsItemProduct';

export type Checkout200OrderItemsItem = {
  product: Checkout200OrderItemsItemProduct;
};
