/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { Checkout200OrderItemsItem } from './checkout200OrderItemsItem';

/**
 * @nullable
 */
export type Checkout200Order = {
  id: string;
  items: Checkout200OrderItemsItem[];
} | null;
