/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { Checkout200Order } from './checkout200Order';

export type Checkout200 = {
  /** @nullable */
  order: Checkout200Order;
};
