/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCouponBodyType } from './createCouponBodyType';
import type { CreateCouponBodyScope } from './createCouponBodyScope';

export type CreateCouponBody = {
  /** @minLength 1 */
  code: string;
  type: CreateCouponBodyType;
  scope: CreateCouponBodyScope;
  isActive?: boolean;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  value: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  minOrderValue?: number;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  maxUses?: number;
  expiresAt?: unknown;
  productIds?: string[];
};
