/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrderBodyStatus } from './createOrderBodyStatus';
import type { CreateOrderBodyPaymentMethod } from './createOrderBodyPaymentMethod';
import type { CreateOrderBodyItemsItem } from './createOrderBodyItemsItem';

export type CreateOrderBody = {
  status?: CreateOrderBodyStatus;
  paymentMethod: CreateOrderBodyPaymentMethod;
  /** @pattern ^[cC][^\s-]{8,}$ */
  addressId: string;
  couponCode?: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  deliveryFee?: number;
  /** @minItems 1 */
  items: CreateOrderBodyItemsItem[];
};
