/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type CreateCouponBodyScope = typeof CreateCouponBodyScope[keyof typeof CreateCouponBodyScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateCouponBodyScope = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCTS: 'PRODUCTS',
} as const;
