/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type CreateProductBody = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  slug: string;
  /** @minLength 1 */
  description: string;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  price: number;
  image: string;
  /** @pattern ^[cC][^\s-]{8,}$ */
  categoryId: string;
  popular?: boolean;
  available?: boolean;
};
