/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type CreateCouponBodyType = typeof CreateCouponBodyType[keyof typeof CreateCouponBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateCouponBodyType = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
} as const;
