/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type CreateAddressBody = {
  /** @minLength 1 */
  street: string;
  name: string;
  complement?: string;
  number?: number;
  neighborhood: string;
  /** @minLength 1 */
  city: string;
  /** @minLength 1 */
  zipCode: string;
  isDefault?: boolean;
};
