/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type DeleteProduct204 = typeof DeleteProduct204[keyof typeof DeleteProduct204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteProduct204 = {
} as const;
