/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type DeleteOrder204 = typeof DeleteOrder204[keyof typeof DeleteOrder204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteOrder204 = {
} as const;
