/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetAddressById200Address = {
  /** @nullable */
  number: number | null;
  street: string;
  /** @nullable */
  complement: string | null;
  /** @nullable */
  neighborhood: string | null;
  city: string;
  zipCode: string;
  isDefault: boolean;
  id: string;
  customerId: string;
};
