/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetAddressesByUser200AddressesItem } from './getAddressesByUser200AddressesItem';

export type GetAddressesByUser200 = {
  addresses: GetAddressesByUser200AddressesItem[];
};
