/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetAddresses200AddressesItem } from './getAddresses200AddressesItem';

export type GetAddresses200 = {
  addresses: GetAddresses200AddressesItem[];
};
