/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetAddressById200Address } from './getAddressById200Address';

export type GetAddressById200 = {
  address: GetAddressById200Address;
};
