/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetCoupons200CouponsItemScope = typeof GetCoupons200CouponsItemScope[keyof typeof GetCoupons200CouponsItemScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCoupons200CouponsItemScope = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCTS: 'PRODUCTS',
} as const;
