/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetCoupons200CouponsItem } from './getCoupons200CouponsItem';
import type { GetCoupons200Pagination } from './getCoupons200Pagination';

export type GetCoupons200 = {
  coupons: GetCoupons200CouponsItem[];
  pagination: GetCoupons200Pagination;
};
