/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetCoupons200Pagination = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limit: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  total: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
};
