/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetCouponById200Coupon } from './getCouponById200Coupon';

export type GetCouponById200 = {
  coupon: GetCouponById200Coupon;
};
