/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetCouponById200CouponScope = typeof GetCouponById200CouponScope[keyof typeof GetCouponById200CouponScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCouponById200CouponScope = {
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PRODUCTS: 'PRODUCTS',
} as const;
