/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetCoupons200CouponsItemType } from './getCoupons200CouponsItemType';
import type { GetCoupons200CouponsItemScope } from './getCoupons200CouponsItemScope';
import type { GetCoupons200CouponsItemUsagesItem } from './getCoupons200CouponsItemUsagesItem';
import type { GetCoupons200CouponsItemProductsItem } from './getCoupons200CouponsItemProductsItem';

export type GetCoupons200CouponsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  code: string;
  type: GetCoupons200CouponsItemType;
  scope: GetCoupons200CouponsItemScope;
  value: number;
  /** @nullable */
  minOrderValue: number | null;
  /** @nullable */
  maxUses: number | null;
  usedCount: number;
  /** @nullable */
  expiresAt: string | null;
  isActive: boolean;
  createdAt: string;
  usages: GetCoupons200CouponsItemUsagesItem[];
  products: GetCoupons200CouponsItemProductsItem[];
};
