/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetCoupons200CouponsItemType = typeof GetCoupons200CouponsItemType[keyof typeof GetCoupons200CouponsItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCoupons200CouponsItemType = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
} as const;
