/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetCouponById200CouponType } from './getCouponById200CouponType';
import type { GetCouponById200CouponScope } from './getCouponById200CouponScope';
import type { GetCouponById200CouponUsagesItem } from './getCouponById200CouponUsagesItem';
import type { GetCouponById200CouponProductsItem } from './getCouponById200CouponProductsItem';

export type GetCouponById200Coupon = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  code: string;
  type: GetCouponById200CouponType;
  scope: GetCouponById200CouponScope;
  value: number;
  /** @nullable */
  minOrderValue: number | null;
  /** @nullable */
  maxUses: number | null;
  usedCount: number;
  /** @nullable */
  expiresAt: string | null;
  isActive: boolean;
  createdAt: string;
  usages: GetCouponById200CouponUsagesItem[];
  products: GetCouponById200CouponProductsItem[];
};
