/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetCouponById200CouponType = typeof GetCouponById200CouponType[keyof typeof GetCouponById200CouponType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCouponById200CouponType = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
} as const;
