/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersByCustomer200OrdersItemItemsItemProduct } from './getOrdersByCustomer200OrdersItemItemsItemProduct';

export type GetOrdersByCustomer200OrdersItemItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  quantity: number;
  unitPrice: number;
  product: GetOrdersByCustomer200OrdersItemItemsItemProduct;
};
