/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrderById200OrderItemsItemProduct } from './getOrderById200OrderItemsItemProduct';

export type GetOrderById200OrderItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  quantity: number;
  unitPrice: number;
  product: GetOrderById200OrderItemsItemProduct;
};
