/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetOrders200OrdersItemItemsItemProduct = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  slug: string;
};
