/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetOrders200OrdersItemAddress = {
  /** @nullable */
  number: number | null;
  /** @nullable */
  name: string | null;
  street: string;
  /** @nullable */
  complement: string | null;
  /** @nullable */
  neighborhood: string | null;
  city: string;
  zipCode: string;
} | null;
