/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrderById200Order } from './getOrderById200Order';

export type GetOrderById200 = {
  order: GetOrderById200Order;
};
