/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersByCustomer200OrdersItem } from './getOrdersByCustomer200OrdersItem';
import type { GetOrdersByCustomer200Pagination } from './getOrdersByCustomer200Pagination';

export type GetOrdersByCustomer200 = {
  orders: GetOrdersByCustomer200OrdersItem[];
  pagination: GetOrdersByCustomer200Pagination;
};
