/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrders200OrdersItem } from './getOrders200OrdersItem';
import type { GetOrders200Pagination } from './getOrders200Pagination';

export type GetOrders200 = {
  orders: GetOrders200OrdersItem[];
  pagination: GetOrders200Pagination;
};
