/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersStatus } from './getOrdersStatus';

export type GetOrdersParams = {
page?: string;
limit?: string;
status?: GetOrdersStatus;
search?: string;
/**
 * @pattern ^[cC][^\s-]{8,}$
 */
customerId?: string;
startDate?: unknown;
endDate?: unknown;
};
