/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrders200OrdersItemStatus } from './getOrders200OrdersItemStatus';
import type { GetOrders200OrdersItemPaymentMethod } from './getOrders200OrdersItemPaymentMethod';
import type { GetOrders200OrdersItemCustomer } from './getOrders200OrdersItemCustomer';
import type { GetOrders200OrdersItemItemsItem } from './getOrders200OrdersItemItemsItem';
import type { GetOrders200OrdersItemAddress } from './getOrders200OrdersItemAddress';

export type GetOrders200OrdersItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  orderNumber: number;
  status: GetOrders200OrdersItemStatus;
  paymentMethod: GetOrders200OrdersItemPaymentMethod;
  total: number;
  itemsCount: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  customer: GetOrders200OrdersItemCustomer;
  items: GetOrders200OrdersItemItemsItem[];
  /** @nullable */
  address: GetOrders200OrdersItemAddress;
};
