/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetOrders200OrdersItemPaymentMethod = typeof GetOrders200OrdersItemPaymentMethod[keyof typeof GetOrders200OrdersItemPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrders200OrdersItemPaymentMethod = {
  CASH: 'CASH',
  PIX: 'PIX',
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
} as const;
