/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetOrderById200OrderAddress = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  street: string;
  /** @nullable */
  number: number | null;
  /** @nullable */
  complement: string | null;
  neighborhood: string;
  city: string;
  zipCode: string;
};
