/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetOrders200OrdersItemStatus = typeof GetOrders200OrdersItemStatus[keyof typeof GetOrders200OrdersItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrders200OrdersItemStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;
