/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrderById200OrderStatus } from './getOrderById200OrderStatus';
import type { GetOrderById200OrderPaymentMethod } from './getOrderById200OrderPaymentMethod';
import type { GetOrderById200OrderItemsItem } from './getOrderById200OrderItemsItem';
import type { GetOrderById200OrderCustomer } from './getOrderById200OrderCustomer';
import type { GetOrderById200OrderAddress } from './getOrderById200OrderAddress';

export type GetOrderById200Order = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  orderNumber: number;
  status: GetOrderById200OrderStatus;
  paymentMethod: GetOrderById200OrderPaymentMethod;
  items: GetOrderById200OrderItemsItem[];
  itemsCount: number;
  itemsTotal: number;
  deliveryFee: number;
  total: number;
  createdAt: string;
  updatedAt: string;
  customer: GetOrderById200OrderCustomer;
  address: GetOrderById200OrderAddress;
};
