/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersByCustomer200OrdersItemStatus } from './getOrdersByCustomer200OrdersItemStatus';
import type { GetOrdersByCustomer200OrdersItemCustomer } from './getOrdersByCustomer200OrdersItemCustomer';
import type { GetOrdersByCustomer200OrdersItemItemsItem } from './getOrdersByCustomer200OrdersItemItemsItem';
import type { GetOrdersByCustomer200OrdersItemAddress } from './getOrdersByCustomer200OrdersItemAddress';

export type GetOrdersByCustomer200OrdersItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  status: GetOrdersByCustomer200OrdersItemStatus;
  createdAt: string;
  updatedAt: string;
  total: number;
  itemsCount: number;
  customer: GetOrdersByCustomer200OrdersItemCustomer;
  items: GetOrdersByCustomer200OrdersItemItemsItem[];
  address: GetOrdersByCustomer200OrdersItemAddress;
};
