/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetProfile200UserRole = typeof GetProfile200UserRole[keyof typeof GetProfile200UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetProfile200UserRole = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
} as const;
