/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetProfile200User } from './getProfile200User';

export type GetProfile200 = {
  user: GetProfile200User;
};
