/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetProducts200ProductsItem } from './getProducts200ProductsItem';

export type GetProducts200 = {
  products: GetProducts200ProductsItem[];
  total: number;
  page: number;
  limit: number;
};
