/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersRole } from './getUsersRole';

export type GetUsersParams = {
role?: GetUsersRole;
page?: string;
limit?: string;
search?: string;
};
