/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsers200UsersItem } from './getUsers200UsersItem';
import type { GetUsers200Pagination } from './getUsers200Pagination';

export type GetUsers200 = {
  users: GetUsers200UsersItem[];
  pagination: GetUsers200Pagination;
};
