/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type GetUsers200UsersItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @nullable */
  name: string | null;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  city: string | null;
  joinDate: string;
};
