/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type RequestPasswordRecover201 = typeof RequestPasswordRecover201[keyof typeof RequestPasswordRecover201] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestPasswordRecover201 = {
} as const;
