/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ResetPassword204 = typeof ResetPassword204[keyof typeof ResetPassword204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResetPassword204 = {
} as const;
