/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrderBodyItemsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  productId: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  quantity: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  unitPrice: number;
};
