/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCouponBodyScope } from './updateCouponBodyScope';
import type { UpdateCouponBodyExpiresAt } from './updateCouponBodyExpiresAt';

export type UpdateCouponBody = {
  code?: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  value?: number;
  isActive?: boolean;
  /**
   * @minimum 0
   * @exclusiveMinimum
   * @nullable
   */
  minOrderValue?: number | null;
  scope?: UpdateCouponBodyScope;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   * @nullable
   */
  maxUses?: number | null;
  /** @nullable */
  expiresAt?: UpdateCouponBodyExpiresAt;
  productIds?: string[];
};
