/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UpdateCoupon204 = typeof UpdateCoupon204[keyof typeof UpdateCoupon204] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCoupon204 = {
} as const;
