/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrderBodyPaymentMethod = typeof UpdateOrderBodyPaymentMethod[keyof typeof UpdateOrderBodyPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateOrderBodyPaymentMethod = {
  CASH: 'CASH',
  PIX: 'PIX',
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
} as const;
