/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrderBodyPaymentMethod } from './updateOrderBodyPaymentMethod';
import type { UpdateOrderBodyStatus } from './updateOrderBodyStatus';
import type { UpdateOrderBodyItemsItem } from './updateOrderBodyItemsItem';

export type UpdateOrderBody = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  addressId?: string;
  paymentMethod?: UpdateOrderBodyPaymentMethod;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  changeFor?: number;
  status?: UpdateOrderBodyStatus;
  /**
   * @nullable
   * @pattern ^[cC][^\s-]{8,}$
   */
  couponId?: string | null;
  items?: UpdateOrderBodyItemsItem[];
};
