/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Api Documentation - Menu Digital
 * API documentation for Menu digital
 * OpenAPI spec version: 1.0.0
 */

export type ValidateCouponBody = {
  code: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  orderTotal: number;
  /** @minItems 1 */
  productIds: string[];
};
